// Copyright 2018-2023 Polyaxon, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by go-swagger; DO NOT EDIT.

package organizations_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/polyaxon/sdks/go/http_client/v1/service_model"
)

// GetOrganizationReader is a Reader for the GetOrganization structure.
type GetOrganizationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetOrganizationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetOrganizationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 204:
		result := NewGetOrganizationNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewGetOrganizationForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetOrganizationNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewGetOrganizationDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetOrganizationOK creates a GetOrganizationOK with default headers values
func NewGetOrganizationOK() *GetOrganizationOK {
	return &GetOrganizationOK{}
}

/* GetOrganizationOK describes a response with status code 200, with default header values.

A successful response.
*/
type GetOrganizationOK struct {
	Payload *service_model.V1Organization
}

// IsSuccess returns true when this get organization o k response has a 2xx status code
func (o *GetOrganizationOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get organization o k response has a 3xx status code
func (o *GetOrganizationOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get organization o k response has a 4xx status code
func (o *GetOrganizationOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get organization o k response has a 5xx status code
func (o *GetOrganizationOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get organization o k response a status code equal to that given
func (o *GetOrganizationOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetOrganizationOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/orgs/{owner}][%d] getOrganizationOK  %+v", 200, o.Payload)
}

func (o *GetOrganizationOK) String() string {
	return fmt.Sprintf("[GET /api/v1/orgs/{owner}][%d] getOrganizationOK  %+v", 200, o.Payload)
}

func (o *GetOrganizationOK) GetPayload() *service_model.V1Organization {
	return o.Payload
}

func (o *GetOrganizationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(service_model.V1Organization)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetOrganizationNoContent creates a GetOrganizationNoContent with default headers values
func NewGetOrganizationNoContent() *GetOrganizationNoContent {
	return &GetOrganizationNoContent{}
}

/* GetOrganizationNoContent describes a response with status code 204, with default header values.

No content.
*/
type GetOrganizationNoContent struct {
	Payload interface{}
}

// IsSuccess returns true when this get organization no content response has a 2xx status code
func (o *GetOrganizationNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get organization no content response has a 3xx status code
func (o *GetOrganizationNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get organization no content response has a 4xx status code
func (o *GetOrganizationNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this get organization no content response has a 5xx status code
func (o *GetOrganizationNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this get organization no content response a status code equal to that given
func (o *GetOrganizationNoContent) IsCode(code int) bool {
	return code == 204
}

func (o *GetOrganizationNoContent) Error() string {
	return fmt.Sprintf("[GET /api/v1/orgs/{owner}][%d] getOrganizationNoContent  %+v", 204, o.Payload)
}

func (o *GetOrganizationNoContent) String() string {
	return fmt.Sprintf("[GET /api/v1/orgs/{owner}][%d] getOrganizationNoContent  %+v", 204, o.Payload)
}

func (o *GetOrganizationNoContent) GetPayload() interface{} {
	return o.Payload
}

func (o *GetOrganizationNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetOrganizationForbidden creates a GetOrganizationForbidden with default headers values
func NewGetOrganizationForbidden() *GetOrganizationForbidden {
	return &GetOrganizationForbidden{}
}

/* GetOrganizationForbidden describes a response with status code 403, with default header values.

You don't have permission to access the resource.
*/
type GetOrganizationForbidden struct {
	Payload interface{}
}

// IsSuccess returns true when this get organization forbidden response has a 2xx status code
func (o *GetOrganizationForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get organization forbidden response has a 3xx status code
func (o *GetOrganizationForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get organization forbidden response has a 4xx status code
func (o *GetOrganizationForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get organization forbidden response has a 5xx status code
func (o *GetOrganizationForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get organization forbidden response a status code equal to that given
func (o *GetOrganizationForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *GetOrganizationForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v1/orgs/{owner}][%d] getOrganizationForbidden  %+v", 403, o.Payload)
}

func (o *GetOrganizationForbidden) String() string {
	return fmt.Sprintf("[GET /api/v1/orgs/{owner}][%d] getOrganizationForbidden  %+v", 403, o.Payload)
}

func (o *GetOrganizationForbidden) GetPayload() interface{} {
	return o.Payload
}

func (o *GetOrganizationForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetOrganizationNotFound creates a GetOrganizationNotFound with default headers values
func NewGetOrganizationNotFound() *GetOrganizationNotFound {
	return &GetOrganizationNotFound{}
}

/* GetOrganizationNotFound describes a response with status code 404, with default header values.

Resource does not exist.
*/
type GetOrganizationNotFound struct {
	Payload interface{}
}

// IsSuccess returns true when this get organization not found response has a 2xx status code
func (o *GetOrganizationNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get organization not found response has a 3xx status code
func (o *GetOrganizationNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get organization not found response has a 4xx status code
func (o *GetOrganizationNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get organization not found response has a 5xx status code
func (o *GetOrganizationNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get organization not found response a status code equal to that given
func (o *GetOrganizationNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *GetOrganizationNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v1/orgs/{owner}][%d] getOrganizationNotFound  %+v", 404, o.Payload)
}

func (o *GetOrganizationNotFound) String() string {
	return fmt.Sprintf("[GET /api/v1/orgs/{owner}][%d] getOrganizationNotFound  %+v", 404, o.Payload)
}

func (o *GetOrganizationNotFound) GetPayload() interface{} {
	return o.Payload
}

func (o *GetOrganizationNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetOrganizationDefault creates a GetOrganizationDefault with default headers values
func NewGetOrganizationDefault(code int) *GetOrganizationDefault {
	return &GetOrganizationDefault{
		_statusCode: code,
	}
}

/* GetOrganizationDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type GetOrganizationDefault struct {
	_statusCode int

	Payload *service_model.RuntimeError
}

// Code gets the status code for the get organization default response
func (o *GetOrganizationDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this get organization default response has a 2xx status code
func (o *GetOrganizationDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get organization default response has a 3xx status code
func (o *GetOrganizationDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get organization default response has a 4xx status code
func (o *GetOrganizationDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get organization default response has a 5xx status code
func (o *GetOrganizationDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get organization default response a status code equal to that given
func (o *GetOrganizationDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *GetOrganizationDefault) Error() string {
	return fmt.Sprintf("[GET /api/v1/orgs/{owner}][%d] GetOrganization default  %+v", o._statusCode, o.Payload)
}

func (o *GetOrganizationDefault) String() string {
	return fmt.Sprintf("[GET /api/v1/orgs/{owner}][%d] GetOrganization default  %+v", o._statusCode, o.Payload)
}

func (o *GetOrganizationDefault) GetPayload() *service_model.RuntimeError {
	return o.Payload
}

func (o *GetOrganizationDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(service_model.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
