// Code generated by go-swagger; DO NOT EDIT.

package organizations_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/polyaxon/sdks/go/http_client/v1/service_model"
)

// RestoreOrganizationRunsReader is a Reader for the RestoreOrganizationRuns structure.
type RestoreOrganizationRunsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RestoreOrganizationRunsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewRestoreOrganizationRunsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 204:
		result := NewRestoreOrganizationRunsNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewRestoreOrganizationRunsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewRestoreOrganizationRunsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewRestoreOrganizationRunsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewRestoreOrganizationRunsOK creates a RestoreOrganizationRunsOK with default headers values
func NewRestoreOrganizationRunsOK() *RestoreOrganizationRunsOK {
	return &RestoreOrganizationRunsOK{}
}

/*
RestoreOrganizationRunsOK describes a response with status code 200, with default header values.

A successful response.
*/
type RestoreOrganizationRunsOK struct {
}

// IsSuccess returns true when this restore organization runs o k response has a 2xx status code
func (o *RestoreOrganizationRunsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this restore organization runs o k response has a 3xx status code
func (o *RestoreOrganizationRunsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this restore organization runs o k response has a 4xx status code
func (o *RestoreOrganizationRunsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this restore organization runs o k response has a 5xx status code
func (o *RestoreOrganizationRunsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this restore organization runs o k response a status code equal to that given
func (o *RestoreOrganizationRunsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the restore organization runs o k response
func (o *RestoreOrganizationRunsOK) Code() int {
	return 200
}

func (o *RestoreOrganizationRunsOK) Error() string {
	return fmt.Sprintf("[POST /api/v1/orgs/{owner}/runs/restore][%d] restoreOrganizationRunsOK", 200)
}

func (o *RestoreOrganizationRunsOK) String() string {
	return fmt.Sprintf("[POST /api/v1/orgs/{owner}/runs/restore][%d] restoreOrganizationRunsOK", 200)
}

func (o *RestoreOrganizationRunsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRestoreOrganizationRunsNoContent creates a RestoreOrganizationRunsNoContent with default headers values
func NewRestoreOrganizationRunsNoContent() *RestoreOrganizationRunsNoContent {
	return &RestoreOrganizationRunsNoContent{}
}

/*
RestoreOrganizationRunsNoContent describes a response with status code 204, with default header values.

No content.
*/
type RestoreOrganizationRunsNoContent struct {
	Payload any
}

// IsSuccess returns true when this restore organization runs no content response has a 2xx status code
func (o *RestoreOrganizationRunsNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this restore organization runs no content response has a 3xx status code
func (o *RestoreOrganizationRunsNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this restore organization runs no content response has a 4xx status code
func (o *RestoreOrganizationRunsNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this restore organization runs no content response has a 5xx status code
func (o *RestoreOrganizationRunsNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this restore organization runs no content response a status code equal to that given
func (o *RestoreOrganizationRunsNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the restore organization runs no content response
func (o *RestoreOrganizationRunsNoContent) Code() int {
	return 204
}

func (o *RestoreOrganizationRunsNoContent) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/orgs/{owner}/runs/restore][%d] restoreOrganizationRunsNoContent %s", 204, payload)
}

func (o *RestoreOrganizationRunsNoContent) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/orgs/{owner}/runs/restore][%d] restoreOrganizationRunsNoContent %s", 204, payload)
}

func (o *RestoreOrganizationRunsNoContent) GetPayload() any {
	return o.Payload
}

func (o *RestoreOrganizationRunsNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewRestoreOrganizationRunsForbidden creates a RestoreOrganizationRunsForbidden with default headers values
func NewRestoreOrganizationRunsForbidden() *RestoreOrganizationRunsForbidden {
	return &RestoreOrganizationRunsForbidden{}
}

/*
RestoreOrganizationRunsForbidden describes a response with status code 403, with default header values.

You don't have permission to access the resource.
*/
type RestoreOrganizationRunsForbidden struct {
	Payload any
}

// IsSuccess returns true when this restore organization runs forbidden response has a 2xx status code
func (o *RestoreOrganizationRunsForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this restore organization runs forbidden response has a 3xx status code
func (o *RestoreOrganizationRunsForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this restore organization runs forbidden response has a 4xx status code
func (o *RestoreOrganizationRunsForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this restore organization runs forbidden response has a 5xx status code
func (o *RestoreOrganizationRunsForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this restore organization runs forbidden response a status code equal to that given
func (o *RestoreOrganizationRunsForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the restore organization runs forbidden response
func (o *RestoreOrganizationRunsForbidden) Code() int {
	return 403
}

func (o *RestoreOrganizationRunsForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/orgs/{owner}/runs/restore][%d] restoreOrganizationRunsForbidden %s", 403, payload)
}

func (o *RestoreOrganizationRunsForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/orgs/{owner}/runs/restore][%d] restoreOrganizationRunsForbidden %s", 403, payload)
}

func (o *RestoreOrganizationRunsForbidden) GetPayload() any {
	return o.Payload
}

func (o *RestoreOrganizationRunsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewRestoreOrganizationRunsNotFound creates a RestoreOrganizationRunsNotFound with default headers values
func NewRestoreOrganizationRunsNotFound() *RestoreOrganizationRunsNotFound {
	return &RestoreOrganizationRunsNotFound{}
}

/*
RestoreOrganizationRunsNotFound describes a response with status code 404, with default header values.

Resource does not exist.
*/
type RestoreOrganizationRunsNotFound struct {
	Payload any
}

// IsSuccess returns true when this restore organization runs not found response has a 2xx status code
func (o *RestoreOrganizationRunsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this restore organization runs not found response has a 3xx status code
func (o *RestoreOrganizationRunsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this restore organization runs not found response has a 4xx status code
func (o *RestoreOrganizationRunsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this restore organization runs not found response has a 5xx status code
func (o *RestoreOrganizationRunsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this restore organization runs not found response a status code equal to that given
func (o *RestoreOrganizationRunsNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the restore organization runs not found response
func (o *RestoreOrganizationRunsNotFound) Code() int {
	return 404
}

func (o *RestoreOrganizationRunsNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/orgs/{owner}/runs/restore][%d] restoreOrganizationRunsNotFound %s", 404, payload)
}

func (o *RestoreOrganizationRunsNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/orgs/{owner}/runs/restore][%d] restoreOrganizationRunsNotFound %s", 404, payload)
}

func (o *RestoreOrganizationRunsNotFound) GetPayload() any {
	return o.Payload
}

func (o *RestoreOrganizationRunsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewRestoreOrganizationRunsDefault creates a RestoreOrganizationRunsDefault with default headers values
func NewRestoreOrganizationRunsDefault(code int) *RestoreOrganizationRunsDefault {
	return &RestoreOrganizationRunsDefault{
		_statusCode: code,
	}
}

/*
RestoreOrganizationRunsDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type RestoreOrganizationRunsDefault struct {
	_statusCode int

	Payload *service_model.RuntimeError
}

// IsSuccess returns true when this restore organization runs default response has a 2xx status code
func (o *RestoreOrganizationRunsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this restore organization runs default response has a 3xx status code
func (o *RestoreOrganizationRunsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this restore organization runs default response has a 4xx status code
func (o *RestoreOrganizationRunsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this restore organization runs default response has a 5xx status code
func (o *RestoreOrganizationRunsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this restore organization runs default response a status code equal to that given
func (o *RestoreOrganizationRunsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the restore organization runs default response
func (o *RestoreOrganizationRunsDefault) Code() int {
	return o._statusCode
}

func (o *RestoreOrganizationRunsDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/orgs/{owner}/runs/restore][%d] RestoreOrganizationRuns default %s", o._statusCode, payload)
}

func (o *RestoreOrganizationRunsDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/orgs/{owner}/runs/restore][%d] RestoreOrganizationRuns default %s", o._statusCode, payload)
}

func (o *RestoreOrganizationRunsDefault) GetPayload() *service_model.RuntimeError {
	return o.Payload
}

func (o *RestoreOrganizationRunsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(service_model.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
