// Code generated by go-swagger; DO NOT EDIT.

package runs_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/polyaxon/sdks/go/http_client/v1/service_model"
)

// GetRunStatusesReader is a Reader for the GetRunStatuses structure.
type GetRunStatusesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRunStatusesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetRunStatusesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 204:
		result := NewGetRunStatusesNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewGetRunStatusesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetRunStatusesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewGetRunStatusesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetRunStatusesOK creates a GetRunStatusesOK with default headers values
func NewGetRunStatusesOK() *GetRunStatusesOK {
	return &GetRunStatusesOK{}
}

/*
GetRunStatusesOK describes a response with status code 200, with default header values.

A successful response.
*/
type GetRunStatusesOK struct {
	Payload *service_model.V1Status
}

// IsSuccess returns true when this get run statuses o k response has a 2xx status code
func (o *GetRunStatusesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get run statuses o k response has a 3xx status code
func (o *GetRunStatusesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get run statuses o k response has a 4xx status code
func (o *GetRunStatusesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get run statuses o k response has a 5xx status code
func (o *GetRunStatusesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get run statuses o k response a status code equal to that given
func (o *GetRunStatusesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get run statuses o k response
func (o *GetRunStatusesOK) Code() int {
	return 200
}

func (o *GetRunStatusesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/{owner}/{entity}/runs/{uuid}/statuses][%d] getRunStatusesOK %s", 200, payload)
}

func (o *GetRunStatusesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/{owner}/{entity}/runs/{uuid}/statuses][%d] getRunStatusesOK %s", 200, payload)
}

func (o *GetRunStatusesOK) GetPayload() *service_model.V1Status {
	return o.Payload
}

func (o *GetRunStatusesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(service_model.V1Status)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetRunStatusesNoContent creates a GetRunStatusesNoContent with default headers values
func NewGetRunStatusesNoContent() *GetRunStatusesNoContent {
	return &GetRunStatusesNoContent{}
}

/*
GetRunStatusesNoContent describes a response with status code 204, with default header values.

No content.
*/
type GetRunStatusesNoContent struct {
	Payload any
}

// IsSuccess returns true when this get run statuses no content response has a 2xx status code
func (o *GetRunStatusesNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get run statuses no content response has a 3xx status code
func (o *GetRunStatusesNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get run statuses no content response has a 4xx status code
func (o *GetRunStatusesNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this get run statuses no content response has a 5xx status code
func (o *GetRunStatusesNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this get run statuses no content response a status code equal to that given
func (o *GetRunStatusesNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the get run statuses no content response
func (o *GetRunStatusesNoContent) Code() int {
	return 204
}

func (o *GetRunStatusesNoContent) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/{owner}/{entity}/runs/{uuid}/statuses][%d] getRunStatusesNoContent %s", 204, payload)
}

func (o *GetRunStatusesNoContent) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/{owner}/{entity}/runs/{uuid}/statuses][%d] getRunStatusesNoContent %s", 204, payload)
}

func (o *GetRunStatusesNoContent) GetPayload() any {
	return o.Payload
}

func (o *GetRunStatusesNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetRunStatusesForbidden creates a GetRunStatusesForbidden with default headers values
func NewGetRunStatusesForbidden() *GetRunStatusesForbidden {
	return &GetRunStatusesForbidden{}
}

/*
GetRunStatusesForbidden describes a response with status code 403, with default header values.

You don't have permission to access the resource.
*/
type GetRunStatusesForbidden struct {
	Payload any
}

// IsSuccess returns true when this get run statuses forbidden response has a 2xx status code
func (o *GetRunStatusesForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get run statuses forbidden response has a 3xx status code
func (o *GetRunStatusesForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get run statuses forbidden response has a 4xx status code
func (o *GetRunStatusesForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get run statuses forbidden response has a 5xx status code
func (o *GetRunStatusesForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get run statuses forbidden response a status code equal to that given
func (o *GetRunStatusesForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get run statuses forbidden response
func (o *GetRunStatusesForbidden) Code() int {
	return 403
}

func (o *GetRunStatusesForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/{owner}/{entity}/runs/{uuid}/statuses][%d] getRunStatusesForbidden %s", 403, payload)
}

func (o *GetRunStatusesForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/{owner}/{entity}/runs/{uuid}/statuses][%d] getRunStatusesForbidden %s", 403, payload)
}

func (o *GetRunStatusesForbidden) GetPayload() any {
	return o.Payload
}

func (o *GetRunStatusesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetRunStatusesNotFound creates a GetRunStatusesNotFound with default headers values
func NewGetRunStatusesNotFound() *GetRunStatusesNotFound {
	return &GetRunStatusesNotFound{}
}

/*
GetRunStatusesNotFound describes a response with status code 404, with default header values.

Resource does not exist.
*/
type GetRunStatusesNotFound struct {
	Payload any
}

// IsSuccess returns true when this get run statuses not found response has a 2xx status code
func (o *GetRunStatusesNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get run statuses not found response has a 3xx status code
func (o *GetRunStatusesNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get run statuses not found response has a 4xx status code
func (o *GetRunStatusesNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get run statuses not found response has a 5xx status code
func (o *GetRunStatusesNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get run statuses not found response a status code equal to that given
func (o *GetRunStatusesNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get run statuses not found response
func (o *GetRunStatusesNotFound) Code() int {
	return 404
}

func (o *GetRunStatusesNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/{owner}/{entity}/runs/{uuid}/statuses][%d] getRunStatusesNotFound %s", 404, payload)
}

func (o *GetRunStatusesNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/{owner}/{entity}/runs/{uuid}/statuses][%d] getRunStatusesNotFound %s", 404, payload)
}

func (o *GetRunStatusesNotFound) GetPayload() any {
	return o.Payload
}

func (o *GetRunStatusesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetRunStatusesDefault creates a GetRunStatusesDefault with default headers values
func NewGetRunStatusesDefault(code int) *GetRunStatusesDefault {
	return &GetRunStatusesDefault{
		_statusCode: code,
	}
}

/*
GetRunStatusesDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type GetRunStatusesDefault struct {
	_statusCode int

	Payload *service_model.RuntimeError
}

// IsSuccess returns true when this get run statuses default response has a 2xx status code
func (o *GetRunStatusesDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get run statuses default response has a 3xx status code
func (o *GetRunStatusesDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get run statuses default response has a 4xx status code
func (o *GetRunStatusesDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get run statuses default response has a 5xx status code
func (o *GetRunStatusesDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get run statuses default response a status code equal to that given
func (o *GetRunStatusesDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get run statuses default response
func (o *GetRunStatusesDefault) Code() int {
	return o._statusCode
}

func (o *GetRunStatusesDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/{owner}/{entity}/runs/{uuid}/statuses][%d] GetRunStatuses default %s", o._statusCode, payload)
}

func (o *GetRunStatusesDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/{owner}/{entity}/runs/{uuid}/statuses][%d] GetRunStatuses default %s", o._statusCode, payload)
}

func (o *GetRunStatusesDefault) GetPayload() *service_model.RuntimeError {
	return o.Payload
}

func (o *GetRunStatusesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(service_model.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
