/**
 * Polyaxon SDKs and REST API specification.
 *
 *
 * The version of the OpenAPI document: 2.12.0-rc8
 * Contact: contact@polyaxon.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The V1RayAutoscalerOptions model module.
 * @module model/V1RayAutoscalerOptions
 * @version 2.12.0-rc8
 */
class V1RayAutoscalerOptions {
    /**
     * Constructs a new <code>V1RayAutoscalerOptions</code>.
     * @alias module:model/V1RayAutoscalerOptions
     */
    constructor() {

        V1RayAutoscalerOptions.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) {
    }

    /**
     * Constructs a <code>V1RayAutoscalerOptions</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1RayAutoscalerOptions} obj Optional instance to populate.
     * @return {module:model/V1RayAutoscalerOptions} The populated <code>V1RayAutoscalerOptions</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1RayAutoscalerOptions();

            if (data.hasOwnProperty('upscalingMode')) {
                obj['upscalingMode'] = ApiClient.convertToType(data['upscalingMode'], 'String');
            }
            if (data.hasOwnProperty('imagePullPolicy')) {
                obj['imagePullPolicy'] = ApiClient.convertToType(data['imagePullPolicy'], 'String');
            }
            if (data.hasOwnProperty('resources')) {
                obj['resources'] = ApiClient.convertToType(data['resources'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>V1RayAutoscalerOptions</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>V1RayAutoscalerOptions</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['upscalingMode'] && !(typeof data['upscalingMode'] === 'string' || data['upscalingMode'] instanceof String)) {
            throw new Error("Expected the field `upscalingMode` to be a primitive type in the JSON string but got " + data['upscalingMode']);
        }
        // ensure the json data is a string
        if (data['imagePullPolicy'] && !(typeof data['imagePullPolicy'] === 'string' || data['imagePullPolicy'] instanceof String)) {
            throw new Error("Expected the field `imagePullPolicy` to be a primitive type in the JSON string but got " + data['imagePullPolicy']);
        }

        return true;
    }


}



/**
 * @member {String} upscalingMode
 */
V1RayAutoscalerOptions.prototype['upscalingMode'] = undefined;

/**
 * @member {String} imagePullPolicy
 */
V1RayAutoscalerOptions.prototype['imagePullPolicy'] = undefined;

/**
 * @member {Object} resources
 */
V1RayAutoscalerOptions.prototype['resources'] = undefined;






export default V1RayAutoscalerOptions;

