// Code generated by go-swagger; DO NOT EDIT.

package service_model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1Flink Flink specification
//
// swagger:model v1Flink
type V1Flink struct {

	// Kind of runtime, should be equal to "flink"
	Kind *string `json:"kind,omitempty"`

	// Flink specification
	Spec interface{} `json:"spec,omitempty"`
}

// Validate validates this v1 flink
func (m *V1Flink) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 flink based on context it is used
func (m *V1Flink) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1Flink) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1Flink) UnmarshalBinary(b []byte) error {
	var res V1Flink
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
