// Code generated by go-swagger; DO NOT EDIT.

package service_model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1ProjectSettings Project Settings specification
//
// swagger:model v1ProjectSettings
type V1ProjectSettings struct {

	// Authorized agents
	Agents []string `json:"agents"`

	// Authorized automations
	Automations []string `json:"automations"`

	// Authorized connections
	Connections []string `json:"connections"`

	// Default Presets
	DefaultPresets []string `json:"default_presets"`

	// Default Presets ordered
	DefaultPresetsOrdered []string `json:"default_presets_ordered"`

	// Authorized namespaces
	Namespaces []string `json:"namespaces"`

	// Attached policy
	Policy string `json:"policy,omitempty"`

	// Authorized Presets
	Presets []string `json:"presets"`

	// Authorized projects
	Projects []string `json:"projects"`

	// Default Queue
	Queue string `json:"queue,omitempty"`

	// Authorized queues
	Queues []string `json:"queues"`

	// Authorized teams
	Teams []string `json:"teams"`

	// Authorized users
	UserAccesses []*V1UserAccess `json:"user_accesses"`
}

// Validate validates this v1 project settings
func (m *V1ProjectSettings) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateUserAccesses(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1ProjectSettings) validateUserAccesses(formats strfmt.Registry) error {
	if swag.IsZero(m.UserAccesses) { // not required
		return nil
	}

	for i := 0; i < len(m.UserAccesses); i++ {
		if swag.IsZero(m.UserAccesses[i]) { // not required
			continue
		}

		if m.UserAccesses[i] != nil {
			if err := m.UserAccesses[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("user_accesses" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("user_accesses" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this v1 project settings based on the context it is used
func (m *V1ProjectSettings) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateUserAccesses(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1ProjectSettings) contextValidateUserAccesses(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.UserAccesses); i++ {

		if m.UserAccesses[i] != nil {

			if swag.IsZero(m.UserAccesses[i]) { // not required
				return nil
			}

			if err := m.UserAccesses[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("user_accesses" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("user_accesses" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1ProjectSettings) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1ProjectSettings) UnmarshalBinary(b []byte) error {
	var res V1ProjectSettings
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
