// Code generated by go-swagger; DO NOT EDIT.

package service_model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// V1Toleration Placeholder for Toleration
//
// swagger:model v1Toleration
type V1Toleration interface{}
