// Code generated by go-swagger; DO NOT EDIT.

package service_model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1Uuids v1 uuids
//
// swagger:model v1Uuids
type V1Uuids struct {

	// uuids
	Uuids []string `json:"uuids"`
}

// Validate validates this v1 uuids
func (m *V1Uuids) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 uuids based on context it is used
func (m *V1Uuids) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1Uuids) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1Uuids) UnmarshalBinary(b []byte) error {
	var res V1Uuids
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
