// Code generated by go-swagger; DO NOT EDIT.

package service_model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1User Auth specification
//
// swagger:model v1User
type V1User struct {

	// Email
	Email string `json:"email,omitempty"`

	// Kind
	Kind string `json:"kind,omitempty"`

	// Name
	Name string `json:"name,omitempty"`

	// Default organization
	Organization string `json:"organization,omitempty"`

	// Theme
	Theme int32 `json:"theme,omitempty"`

	// Username
	Username string `json:"username,omitempty"`
}

// Validate validates this v1 user
func (m *V1User) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 user based on context it is used
func (m *V1User) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1User) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1User) UnmarshalBinary(b []byte) error {
	var res V1User
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
