// Code generated by go-swagger; DO NOT EDIT.

package agents_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/polyaxon/sdks/go/http_client/v1/service_model"
)

// GetAgentStatusesReader is a Reader for the GetAgentStatuses structure.
type GetAgentStatusesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAgentStatusesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAgentStatusesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 204:
		result := NewGetAgentStatusesNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewGetAgentStatusesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetAgentStatusesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewGetAgentStatusesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetAgentStatusesOK creates a GetAgentStatusesOK with default headers values
func NewGetAgentStatusesOK() *GetAgentStatusesOK {
	return &GetAgentStatusesOK{}
}

/*
GetAgentStatusesOK describes a response with status code 200, with default header values.

A successful response.
*/
type GetAgentStatusesOK struct {
	Payload *service_model.V1Status
}

// IsSuccess returns true when this get agent statuses o k response has a 2xx status code
func (o *GetAgentStatusesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get agent statuses o k response has a 3xx status code
func (o *GetAgentStatusesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get agent statuses o k response has a 4xx status code
func (o *GetAgentStatusesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get agent statuses o k response has a 5xx status code
func (o *GetAgentStatusesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get agent statuses o k response a status code equal to that given
func (o *GetAgentStatusesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get agent statuses o k response
func (o *GetAgentStatusesOK) Code() int {
	return 200
}

func (o *GetAgentStatusesOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/orgs/{owner}/agents/{uuid}/statuses][%d] getAgentStatusesOK  %+v", 200, o.Payload)
}

func (o *GetAgentStatusesOK) String() string {
	return fmt.Sprintf("[GET /api/v1/orgs/{owner}/agents/{uuid}/statuses][%d] getAgentStatusesOK  %+v", 200, o.Payload)
}

func (o *GetAgentStatusesOK) GetPayload() *service_model.V1Status {
	return o.Payload
}

func (o *GetAgentStatusesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(service_model.V1Status)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAgentStatusesNoContent creates a GetAgentStatusesNoContent with default headers values
func NewGetAgentStatusesNoContent() *GetAgentStatusesNoContent {
	return &GetAgentStatusesNoContent{}
}

/*
GetAgentStatusesNoContent describes a response with status code 204, with default header values.

No content.
*/
type GetAgentStatusesNoContent struct {
	Payload interface{}
}

// IsSuccess returns true when this get agent statuses no content response has a 2xx status code
func (o *GetAgentStatusesNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get agent statuses no content response has a 3xx status code
func (o *GetAgentStatusesNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get agent statuses no content response has a 4xx status code
func (o *GetAgentStatusesNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this get agent statuses no content response has a 5xx status code
func (o *GetAgentStatusesNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this get agent statuses no content response a status code equal to that given
func (o *GetAgentStatusesNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the get agent statuses no content response
func (o *GetAgentStatusesNoContent) Code() int {
	return 204
}

func (o *GetAgentStatusesNoContent) Error() string {
	return fmt.Sprintf("[GET /api/v1/orgs/{owner}/agents/{uuid}/statuses][%d] getAgentStatusesNoContent  %+v", 204, o.Payload)
}

func (o *GetAgentStatusesNoContent) String() string {
	return fmt.Sprintf("[GET /api/v1/orgs/{owner}/agents/{uuid}/statuses][%d] getAgentStatusesNoContent  %+v", 204, o.Payload)
}

func (o *GetAgentStatusesNoContent) GetPayload() interface{} {
	return o.Payload
}

func (o *GetAgentStatusesNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAgentStatusesForbidden creates a GetAgentStatusesForbidden with default headers values
func NewGetAgentStatusesForbidden() *GetAgentStatusesForbidden {
	return &GetAgentStatusesForbidden{}
}

/*
GetAgentStatusesForbidden describes a response with status code 403, with default header values.

You don't have permission to access the resource.
*/
type GetAgentStatusesForbidden struct {
	Payload interface{}
}

// IsSuccess returns true when this get agent statuses forbidden response has a 2xx status code
func (o *GetAgentStatusesForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get agent statuses forbidden response has a 3xx status code
func (o *GetAgentStatusesForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get agent statuses forbidden response has a 4xx status code
func (o *GetAgentStatusesForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get agent statuses forbidden response has a 5xx status code
func (o *GetAgentStatusesForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get agent statuses forbidden response a status code equal to that given
func (o *GetAgentStatusesForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get agent statuses forbidden response
func (o *GetAgentStatusesForbidden) Code() int {
	return 403
}

func (o *GetAgentStatusesForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v1/orgs/{owner}/agents/{uuid}/statuses][%d] getAgentStatusesForbidden  %+v", 403, o.Payload)
}

func (o *GetAgentStatusesForbidden) String() string {
	return fmt.Sprintf("[GET /api/v1/orgs/{owner}/agents/{uuid}/statuses][%d] getAgentStatusesForbidden  %+v", 403, o.Payload)
}

func (o *GetAgentStatusesForbidden) GetPayload() interface{} {
	return o.Payload
}

func (o *GetAgentStatusesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAgentStatusesNotFound creates a GetAgentStatusesNotFound with default headers values
func NewGetAgentStatusesNotFound() *GetAgentStatusesNotFound {
	return &GetAgentStatusesNotFound{}
}

/*
GetAgentStatusesNotFound describes a response with status code 404, with default header values.

Resource does not exist.
*/
type GetAgentStatusesNotFound struct {
	Payload interface{}
}

// IsSuccess returns true when this get agent statuses not found response has a 2xx status code
func (o *GetAgentStatusesNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get agent statuses not found response has a 3xx status code
func (o *GetAgentStatusesNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get agent statuses not found response has a 4xx status code
func (o *GetAgentStatusesNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get agent statuses not found response has a 5xx status code
func (o *GetAgentStatusesNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get agent statuses not found response a status code equal to that given
func (o *GetAgentStatusesNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get agent statuses not found response
func (o *GetAgentStatusesNotFound) Code() int {
	return 404
}

func (o *GetAgentStatusesNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v1/orgs/{owner}/agents/{uuid}/statuses][%d] getAgentStatusesNotFound  %+v", 404, o.Payload)
}

func (o *GetAgentStatusesNotFound) String() string {
	return fmt.Sprintf("[GET /api/v1/orgs/{owner}/agents/{uuid}/statuses][%d] getAgentStatusesNotFound  %+v", 404, o.Payload)
}

func (o *GetAgentStatusesNotFound) GetPayload() interface{} {
	return o.Payload
}

func (o *GetAgentStatusesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAgentStatusesDefault creates a GetAgentStatusesDefault with default headers values
func NewGetAgentStatusesDefault(code int) *GetAgentStatusesDefault {
	return &GetAgentStatusesDefault{
		_statusCode: code,
	}
}

/*
GetAgentStatusesDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type GetAgentStatusesDefault struct {
	_statusCode int

	Payload *service_model.RuntimeError
}

// IsSuccess returns true when this get agent statuses default response has a 2xx status code
func (o *GetAgentStatusesDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get agent statuses default response has a 3xx status code
func (o *GetAgentStatusesDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get agent statuses default response has a 4xx status code
func (o *GetAgentStatusesDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get agent statuses default response has a 5xx status code
func (o *GetAgentStatusesDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get agent statuses default response a status code equal to that given
func (o *GetAgentStatusesDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get agent statuses default response
func (o *GetAgentStatusesDefault) Code() int {
	return o._statusCode
}

func (o *GetAgentStatusesDefault) Error() string {
	return fmt.Sprintf("[GET /api/v1/orgs/{owner}/agents/{uuid}/statuses][%d] GetAgentStatuses default  %+v", o._statusCode, o.Payload)
}

func (o *GetAgentStatusesDefault) String() string {
	return fmt.Sprintf("[GET /api/v1/orgs/{owner}/agents/{uuid}/statuses][%d] GetAgentStatuses default  %+v", o._statusCode, o.Payload)
}

func (o *GetAgentStatusesDefault) GetPayload() *service_model.RuntimeError {
	return o.Payload
}

func (o *GetAgentStatusesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(service_model.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
