// Code generated by go-swagger; DO NOT EDIT.

package service_accounts_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/polyaxon/sdks/go/http_client/v1/service_model"
)

// PatchServiceAccountReader is a Reader for the PatchServiceAccount structure.
type PatchServiceAccountReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchServiceAccountReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPatchServiceAccountOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 204:
		result := NewPatchServiceAccountNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewPatchServiceAccountForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPatchServiceAccountNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewPatchServiceAccountDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPatchServiceAccountOK creates a PatchServiceAccountOK with default headers values
func NewPatchServiceAccountOK() *PatchServiceAccountOK {
	return &PatchServiceAccountOK{}
}

/*
PatchServiceAccountOK describes a response with status code 200, with default header values.

A successful response.
*/
type PatchServiceAccountOK struct {
	Payload *service_model.V1ServiceAccount
}

// IsSuccess returns true when this patch service account o k response has a 2xx status code
func (o *PatchServiceAccountOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this patch service account o k response has a 3xx status code
func (o *PatchServiceAccountOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this patch service account o k response has a 4xx status code
func (o *PatchServiceAccountOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this patch service account o k response has a 5xx status code
func (o *PatchServiceAccountOK) IsServerError() bool {
	return false
}

// IsCode returns true when this patch service account o k response a status code equal to that given
func (o *PatchServiceAccountOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the patch service account o k response
func (o *PatchServiceAccountOK) Code() int {
	return 200
}

func (o *PatchServiceAccountOK) Error() string {
	return fmt.Sprintf("[PATCH /api/v1/orgs/{owner}/sa/{sa.uuid}][%d] patchServiceAccountOK  %+v", 200, o.Payload)
}

func (o *PatchServiceAccountOK) String() string {
	return fmt.Sprintf("[PATCH /api/v1/orgs/{owner}/sa/{sa.uuid}][%d] patchServiceAccountOK  %+v", 200, o.Payload)
}

func (o *PatchServiceAccountOK) GetPayload() *service_model.V1ServiceAccount {
	return o.Payload
}

func (o *PatchServiceAccountOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(service_model.V1ServiceAccount)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPatchServiceAccountNoContent creates a PatchServiceAccountNoContent with default headers values
func NewPatchServiceAccountNoContent() *PatchServiceAccountNoContent {
	return &PatchServiceAccountNoContent{}
}

/*
PatchServiceAccountNoContent describes a response with status code 204, with default header values.

No content.
*/
type PatchServiceAccountNoContent struct {
	Payload interface{}
}

// IsSuccess returns true when this patch service account no content response has a 2xx status code
func (o *PatchServiceAccountNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this patch service account no content response has a 3xx status code
func (o *PatchServiceAccountNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this patch service account no content response has a 4xx status code
func (o *PatchServiceAccountNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this patch service account no content response has a 5xx status code
func (o *PatchServiceAccountNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this patch service account no content response a status code equal to that given
func (o *PatchServiceAccountNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the patch service account no content response
func (o *PatchServiceAccountNoContent) Code() int {
	return 204
}

func (o *PatchServiceAccountNoContent) Error() string {
	return fmt.Sprintf("[PATCH /api/v1/orgs/{owner}/sa/{sa.uuid}][%d] patchServiceAccountNoContent  %+v", 204, o.Payload)
}

func (o *PatchServiceAccountNoContent) String() string {
	return fmt.Sprintf("[PATCH /api/v1/orgs/{owner}/sa/{sa.uuid}][%d] patchServiceAccountNoContent  %+v", 204, o.Payload)
}

func (o *PatchServiceAccountNoContent) GetPayload() interface{} {
	return o.Payload
}

func (o *PatchServiceAccountNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPatchServiceAccountForbidden creates a PatchServiceAccountForbidden with default headers values
func NewPatchServiceAccountForbidden() *PatchServiceAccountForbidden {
	return &PatchServiceAccountForbidden{}
}

/*
PatchServiceAccountForbidden describes a response with status code 403, with default header values.

You don't have permission to access the resource.
*/
type PatchServiceAccountForbidden struct {
	Payload interface{}
}

// IsSuccess returns true when this patch service account forbidden response has a 2xx status code
func (o *PatchServiceAccountForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this patch service account forbidden response has a 3xx status code
func (o *PatchServiceAccountForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this patch service account forbidden response has a 4xx status code
func (o *PatchServiceAccountForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this patch service account forbidden response has a 5xx status code
func (o *PatchServiceAccountForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this patch service account forbidden response a status code equal to that given
func (o *PatchServiceAccountForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the patch service account forbidden response
func (o *PatchServiceAccountForbidden) Code() int {
	return 403
}

func (o *PatchServiceAccountForbidden) Error() string {
	return fmt.Sprintf("[PATCH /api/v1/orgs/{owner}/sa/{sa.uuid}][%d] patchServiceAccountForbidden  %+v", 403, o.Payload)
}

func (o *PatchServiceAccountForbidden) String() string {
	return fmt.Sprintf("[PATCH /api/v1/orgs/{owner}/sa/{sa.uuid}][%d] patchServiceAccountForbidden  %+v", 403, o.Payload)
}

func (o *PatchServiceAccountForbidden) GetPayload() interface{} {
	return o.Payload
}

func (o *PatchServiceAccountForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPatchServiceAccountNotFound creates a PatchServiceAccountNotFound with default headers values
func NewPatchServiceAccountNotFound() *PatchServiceAccountNotFound {
	return &PatchServiceAccountNotFound{}
}

/*
PatchServiceAccountNotFound describes a response with status code 404, with default header values.

Resource does not exist.
*/
type PatchServiceAccountNotFound struct {
	Payload interface{}
}

// IsSuccess returns true when this patch service account not found response has a 2xx status code
func (o *PatchServiceAccountNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this patch service account not found response has a 3xx status code
func (o *PatchServiceAccountNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this patch service account not found response has a 4xx status code
func (o *PatchServiceAccountNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this patch service account not found response has a 5xx status code
func (o *PatchServiceAccountNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this patch service account not found response a status code equal to that given
func (o *PatchServiceAccountNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the patch service account not found response
func (o *PatchServiceAccountNotFound) Code() int {
	return 404
}

func (o *PatchServiceAccountNotFound) Error() string {
	return fmt.Sprintf("[PATCH /api/v1/orgs/{owner}/sa/{sa.uuid}][%d] patchServiceAccountNotFound  %+v", 404, o.Payload)
}

func (o *PatchServiceAccountNotFound) String() string {
	return fmt.Sprintf("[PATCH /api/v1/orgs/{owner}/sa/{sa.uuid}][%d] patchServiceAccountNotFound  %+v", 404, o.Payload)
}

func (o *PatchServiceAccountNotFound) GetPayload() interface{} {
	return o.Payload
}

func (o *PatchServiceAccountNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPatchServiceAccountDefault creates a PatchServiceAccountDefault with default headers values
func NewPatchServiceAccountDefault(code int) *PatchServiceAccountDefault {
	return &PatchServiceAccountDefault{
		_statusCode: code,
	}
}

/*
PatchServiceAccountDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type PatchServiceAccountDefault struct {
	_statusCode int

	Payload *service_model.RuntimeError
}

// IsSuccess returns true when this patch service account default response has a 2xx status code
func (o *PatchServiceAccountDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this patch service account default response has a 3xx status code
func (o *PatchServiceAccountDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this patch service account default response has a 4xx status code
func (o *PatchServiceAccountDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this patch service account default response has a 5xx status code
func (o *PatchServiceAccountDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this patch service account default response a status code equal to that given
func (o *PatchServiceAccountDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the patch service account default response
func (o *PatchServiceAccountDefault) Code() int {
	return o._statusCode
}

func (o *PatchServiceAccountDefault) Error() string {
	return fmt.Sprintf("[PATCH /api/v1/orgs/{owner}/sa/{sa.uuid}][%d] PatchServiceAccount default  %+v", o._statusCode, o.Payload)
}

func (o *PatchServiceAccountDefault) String() string {
	return fmt.Sprintf("[PATCH /api/v1/orgs/{owner}/sa/{sa.uuid}][%d] PatchServiceAccount default  %+v", o._statusCode, o.Payload)
}

func (o *PatchServiceAccountDefault) GetPayload() *service_model.RuntimeError {
	return o.Payload
}

func (o *PatchServiceAccountDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(service_model.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
